### ISSUE TITLE
Drag & Drop not working on Windows 8.1

### ISSUE THREAD

**Issue by zeeshanjan82** [codef0rmer/angular-dragdrop#192] opened 2015-06-20 14:06 UTC
I am not able to run the samples or even run my code which uses Angular Drag and Drop library on Windows 8.1 touch screen.

Is there any way to make it run with touch on windows 8.1

**Comment by codef0rmer** [comment] 2015-09-06 13:51
Use touchpunch.js. Duplicate of #186

**Closed by codef0rmer** 2015-09-06 13:51 UTC
